### **PART 1**

In [ ]:
import pandas as pd
import math
import numpy as np

In [ ]:
corpus = ['It is going to rain today' , 'Today I am not going outside because I think it might rain', 'I am going to watch the rains this season']
words_set = set()
for aa in corpus:
    words = aa.split(' ')
    words_set = words_set.union(set(words))
print('Number of words in the corpus:',len(words_set))
print('The words in the corpus: \n', words_set)

Number of words in the corpus: 20
The words in the corpus:
 {'outside', 'to', 'watch', 'this', 'is', 'am', 'Today', 'season', 'might', 'It', 'the', 'I', 'rains', 'today', 'rain', 'going', 'because', 'not', 'think', 'it'}

In [ ]:
n_docs = len(corpus)         #·Number of documents in the corpus
n_words_set = len(words_set) #·Number of unique words in the 

df_tf = pd.DataFrame(np.zeros((n_docs, n_words_set)), columns=words_set)

# Compute Term Frequency (TF)
for ij in range(n_docs):
    words = corpus[ij].split(' ') # Words in the document
    for ww in words:
        df_tf[ww][ij] = df_tf[ww][ij] + (1 / len(words))
        
df_tf

#def computeTF(words_set, corpus):
#    tfDict = {}
#    corpusCount = len(df_tf)
#    for word, count in df_tf.items():
#        tfDict[word] = count/float(corpusCount)
#    return(tfDict)
#running our sentences through the tf function:
#tf = computeTF(words_set, corpus)
#Converting to dataframe for visualization
#tf = pd.DataFrame(tf)
#print(tf)

,outside,to,watch,this,is,am,Today,season,might,It,the,I,rains,today,rain,going,because,not,think,it
0,0.000000,0.166667,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.000000,0.166667,0.000000,0.000000,0.000000,0.166667,0.166667,0.166667,0.000000,0.000000,0.000000,0.000000
1,0.083333,0.000000,0.000000,0.000000,0.000000,0.083333,0.083333,0.000000,0.083333,0.000000,0.000000,0.166667,0.000000,0.000000,0.083333,0.083333,0.083333,0.083333,0.083333,0.083333
2,0.000000,0.111111,0.111111,0.111111,0.000000,0.111111,0.000000,0.111111,0.000000,0.000000,0.111111,0.111111,0.111111,0.000000,0.000000,0.111111,0.000000,0.000000,0.000000,0.000000

In [ ]:
print("IDF of: ")
invdf = {}
for all in words_set:
    kk = 0    # number of documents in the corpus that contain this word
    for z in range(n_docs):
        if all in corpus[z].split():
            kk += 1
    invdf[all] =  np.log10(n_docs / kk)
    print(f'{all:>15}: {invdf[all]:>10}' )

IDF of:
        outside: 0.47712125471966244
             to: 0.17609125905568124
          watch: 0.47712125471966244
           this: 0.47712125471966244
             is: 0.47712125471966244
             am: 0.17609125905568124
          Today: 0.47712125471966244
         season: 0.47712125471966244
          might: 0.47712125471966244
             It: 0.47712125471966244
            the: 0.47712125471966244
              I: 0.17609125905568124
          rains: 0.47712125471966244
          today: 0.47712125471966244
           rain: 0.17609125905568124
          going:        0.0
        because: 0.47712125471966244
            not: 0.47712125471966244
          think: 0.47712125471966244
             it: 0.47712125471966244

In [ ]:
df_tf_idf = df_tf.copy()

for w in words_set:
    for i in range(n_docs):
        df_tf_idf[w][i] = df_tf[w][i] * invdf[w]
        
df_tf_idf

,outside,to,watch,this,is,am,Today,season,might,It,the,I,rains,today,rain,going,because,not,think,it
0,0.00000,0.029349,0.000000,0.000000,0.07952,0.000000,0.00000,0.000000,0.00000,0.07952,0.000000,0.000000,0.000000,0.07952,0.029349,0.0,0.00000,0.00000,0.00000,0.00000
1,0.03976,0.000000,0.000000,0.000000,0.00000,0.014674,0.03976,0.000000,0.03976,0.00000,0.000000,0.029349,0.000000,0.00000,0.014674,0.0,0.03976,0.03976,0.03976,0.03976
2,0.00000,0.019566,0.053013,0.053013,0.00000,0.019566,0.00000,0.053013,0.00000,0.00000,0.053013,0.019566,0.053013,0.00000,0.000000,0.0,0.00000,0.00000,0.00000,0.00000

### **PART 2**

In [7]:
import nltk
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import drive
import os
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
# Mount Google Drive to access the text files

# Define directory path of text files
dir_path = '/content/drive/MyDrive/ALL-SEM-08/Nlp-lab/stories/'
enc = 'iso-8859-15'
# Initialize a list to store the contents of all text files
corpus = []

# Loop through all the text files in the directory
for file_name in os.listdir(dir_path):
    if file_name.endswith('.txt'):
        # Open each file and read its contents
        with open(os.path.join(dir_path, file_name), 'r', encoding=enc) as file:
            content = file.read()
            # Append the contents of the file to the corpus list
            corpus.append(content)

In [9]:
# initialize the TF-IDF vectorizer
tfidf_vectorizer = TfidfVectorizer(stop_words='english')

In [10]:
# fit and transform the corpus using the vectorizer
tfidf = tfidf_vectorizer.fit_transform(corpus)

In [14]:
# define the question
question = "What was the name of the flute?"
# transform the question using the vectorizer
question_tfidf = tfidf_vectorizer.transform([question])

In [15]:
# calculate the cosine similarity between the question and each document in the corpus
cosine_similarities = cosine_similarity(question_tfidf, tfidf).flatten()

In [16]:
# get the index of the document with the highest cosine similarity
best_index = np.argmax(cosine_similarities)
# print the answer
print(corpus[best_index])

The Spirit and the Flute

The origins of the Flute are lost in history, but the theory is that the
discovery resulted from a voice in the wind blowing across a reed.  Whose
voice was it? From earliest recorded times the flute was played both by the
shepherd and as part of ritual. It appears in Sumarian, Iranian Orphic,
Hermatic Tibetan and many other traditions{.

In Egypt the first flute is shown on early slate dated 4 B.C. and pictures of
the flute were commonly found from 26 B.C.

One of the names of the flute was KHERU or voice. The Egyptian Priests used
them in their Liturgy and flutes have been found and tombs and burial sites,
where they were probably were placed as symbols of life.

In Sumaria the ritual flute was called a Ti_Gi which is thought to mean the
Reed of Life.  One of their Kings formed a cult for the flute, as it filled
the temple with joy.

In China, it was called the Ti, and later named Hsaio, in honor of a King,
who in playing duets with his wife Lung-Ho was said to draw Phoenixes from the
sky.  The Phoenix was often depicted as a flute, as we know meaning
resurrection and life.  its presence often meant there was a great sage.  The
flute is also the emblem of Han Hsaing-Tzu, one of the eight immortals of
Taoism, meaning harmony. In Japan, it was called the Shakuhacki, it was used
by the Zen Buddhists sects as a form of chanting.

It is still used in Turkey in the Mystical whirling ceremony of the Mevlevi
Dervishes. In India krishna is seen playing the flute, and is called the
divine player of the flute, whose song recalls home the souls wandering in
disillusion. His flute is called the flute eternity crying to the dwellers in
time. The Bouncers flute is still played in the Indian Tradition of spiritual
Music.

The flute is unique in being the only instrument played by breath alone.
Breath is commonly identified with life and with the soul. The spiritual power
of the flute is given in the power of music, it is said that music gives the
discipline that raises one to divine peacefulness and bliss, and through music
you can reach the Gods.



Researched by:

The Silver Circle
Toronto.


X-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-X
 Another file downloaded from:                     The NIRVANAnet(tm) Seven

 & the Temple of the Screaming Electron   Taipan Enigma        510/935-5845
 Burn This Flag                           Zardoz               408/363-9766
 realitycheck                             Poindexter Fortran   510/527-1662
 Lies Unlimited                           Mick Freen           801/278-2699
 The New Dork Sublime                     Biffnix              415/864-DORK
 The Shrine                               Rif Raf              206/794-6674
 Planet Mirth                             Simon Jester         510/786-6560

                          "Raw Data for Raw Nerves"
X-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-X